version: '3.4'

services:
  mymazdarelay:
    image: mymazdarelay
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    environment:
      - USERNAME=${MYMAZDA_USERNAME}
      - PASSWORD=${MYMAZDA_PASSWORD}
      - REGION=${MYMAZDA_REGION}